@startuml


class Informasjon
class Metadata {
utgiver : enhet
produsent : enhet [0..*]
beskrivelse : tekst [0..1]
tittel : tekst
hovedspråk : kodet
identifikator : tekst
tema : kodet [1..3]
"dato opprettet" : dato
"dato sist oppdatert" : dato [0..1]
"basert på" : url
}

abstract class enhet {
navn : tekst
organisasjonsnummer : tekst
}

class tema {
    navn : tekst
    type : url
}

Informasjon *-- Metadata : beskriver
Metadata .. enhet
Metadata .. tema


@enduml

